name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - uses: haskell/actions/setup@main
        with:
          ghc-version: 8.10.4
          enable-stack: true

      - uses: actions/setup-node@main
        with:
          node-version: 16

      - uses: actions/cache@main
        id: stack-cache
        with:
          path: ~/.stack
          key: stack-v2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}

      - name: Setup Stack
        if: steps.stack-cache.outputs.cache-hit != 'true'
        run: |
          stack config set system-ghc --global true
          stack config set install-ghc --global false

      - run: stack --local-bin-path . install --flag hakyll:-previewServer --flag hakyll:-watchServer

      - run: npm ci

      - run: ./blog build
      - run: ./blog check --internal-links

      - run: tar cvf build.tar.xz build

      - uses: actions/upload-artifact@main
        with:
          name: blog
          path: build.tar.xz

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@main
        with:
          name: blog

      - run: tar xvf build.tar.xz

      - name: Deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          git init
          git config user.name "GitHub Actions"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git switch --orphan gh-pages
          git add -A
          git commit --allow-empty -m "(⋈◍＞◡＜◍)。✧♡ "
          git push -f "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD
